apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- simple-api-svc.yaml
- simple-api-rollout.yaml
- ingress-simple-api.yaml

images:
- name: skaqud/simple-api
  newTag: RB0.0.6
